version: '3.9'

services:
  postgres-server:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - 8080:8080
    depends_on:
      - postgres-server
    environment:
      spring.datasource.url: jdbc:postgresql://postgres-server:5432/postgres
      spring.datasource.username: postgres
      spring.datasource.password: password


